# Generated by Django 4.0.5 on 2022-06-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
    ]
