# Generated by Django 4.0.5 on 2022-06-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_file_remark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
